# Generated by Django 3.1.2 on 2020-10-22 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(blank=True, max_length=10)),
                ('odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('odo_date_as_of', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('front_tire_psi', models.IntegerField(default=30)),
                ('rear_tire_psi', models.IntegerField(default=30)),
            ],
        ),
    ]
