# Generated by Django 3.1.2 on 2020-10-26 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='front_tire_psi',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='rear_tire_psi',
        ),
        migrations.AddField(
            model_name='specification',
            name='fuel_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
